### ISSUE TITLE
Clicking on AUTHORIZE button does not seem to work

### ISSUE THREAD

**Issue by fercsrti77** [dnplus/streamlit-oauth#14]
After introducing my Google username and password, the pop-up window shows an AUTHORIZE button. However, clicking on it does nothing. Also, when I move the mouse over the button, it disappears.

<img width="593" alt="Screenshot 2024-01-07 at 10 01 10 AM" src="https://github.com/dnplus/streamlit-oauth/assets/31139902/a927cfe1-b529-4e91-af22-bbc7cde707a2">

<img width="620" alt="Screenshot 2024-01-07 at 10 04 57 AM" src="https://github.com/dnplus/streamlit-oauth/assets/31139902/375b87db-c55f-4665-8a99-e4720963c6be">

I have tried these options in Streamlit config.toml:

[server]
port = 8501
**enableCORS = false
enableXsrfProtection = false**

I have also tried with both Firefox and Chrome browsers with the same result

**Comment by dnplus** [comment]
Hi @fercsrti77 
You can try the examples first to see if it has a problem

**Comment by fercsrti77** [comment]
@dnplus thanks for the fast response. I will try example and get back to you.
