### ISSUE TITLE
Error in Streamlit Cloud / Google App Engine

### ISSUE THREAD

**Issue by sudowoodo200** [dnplus/streamlit-oauth#2]
In either environments, the login pop up simply navigates to the duplicate of the original app page and fails to login. I get this error

```
2023-05-29 05:35:28.368 ComponentRequestHandler: GET /home/appuser/venv/lib/python3.9/site-packages/streamlit_oauth/frontend/dist read error

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/web/server/component_request_handler.py", line 55, in get

    with open(abspath, "rb") as file:

IsADirectoryError: [Errno 21] Is a directory: '/home/appuser/venv/lib/python3.9/site-packages/streamlit_oauth/frontend/dist
```

**Comment by sudowoodo200** [comment]
It now freezes at a blank page

<img width="666" alt="image" src="https://github.com/dnplus/streamlit-oauth/assets/76936961/f1d289ab-01ba-4e07-9035-42f1251770fd">

**Comment by dnplus** [comment]
Solved with CORS fixed.

**Comment by vinnividivicci** [comment]
Hello, I'm getting exactly this same error with streamlit-oauth 0.1.4:
```2023-11-16 15:20:05.411 ComponentRequestHandler: GET /home/adminuser/venv/lib/python3.11/site-packages/streamlit_oauth/frontend/dist read error

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.11/site-packages/streamlit/web/server/component_request_handler.py", line 55, in get

    with open(abspath, "rb") as file:

         ^^^^^^^^^^^^^^^^^^^

IsADirectoryError: [Errno 21] Is a directory: '/home/adminuser/venv/lib/python3.11/site-packages/streamlit_oauth/frontend/dist'```

I tried disabling both CORS and Xsrf but it didn't change anything.

I'm running the simple app on Streamlit Cloud.

Thanks for looking into this.

**Comment by dnplus** [comment]
> Hello, I'm getting exactly this same error with streamlit-oauth 0.1.4:
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "/home/adminuser/venv/lib/python3.11/site-packages/streamlit/web/server/component_request_handler.py", line 55, in get
> 
>     with open(abspath, "rb") as file:
> 
>          ^^^^^^^^^^^^^^^^^^^
> 
> IsADirectoryError: [Errno 21] Is a directory: '/home/adminuser/venv/lib/python3.11/site-packages/streamlit_oauth/frontend/dist'
> ```
> 
> I tried disabling both CORS and Xsrf but it didn't change anything.
> 
> I'm running the simple app on Streamlit Cloud.
> 
> Thanks for looking into this.

Can you share how you disable the CORS and Xsrf?

The original post: https://discuss.streamlit.io/t/new-component-streamlit-oauth/40364/12?u=dnplus
