### ISSUE TITLE
Typo in extra-params of Google example

### ISSUE THREAD

**Issue by HobbyProjects** [dnplus/streamlit-oauth#23]
`    result = oauth2.authorize_button(
        name="Continue with Google",
        icon="https://www.google.com.tw/favicon.ico",
        redirect_uri="http://localhost:8501",
        scope="openid email profile",
        key="google",
        extras_params={"prompt": "consent", "access_type": "offline"},
        use_container_width=True,
        pkce='S256',
`

should be `extra_params`

**Comment by dnplus** [comment]
This approach was inherited from the httpx-oauth package, and we do not plan to alter it due to considerations for backward compatibility.
