### ISSUE TITLE
Need help - may not even be a code issue

### ISSUE THREAD

**Issue by HobbyProjects** [dnplus/streamlit-oauth#26]
Would appreciate some help here. After the user clicks the authorize button, they get directed to the authorization endpoint and get a code. They're then redirected to the callback URL - which is in my case is 

https://<base_address>/component/streamlit_oauth.authorize_button/index.html?code=asdffg****

but I see the lib is not sending that code to exchange with a token. The URL just displays the authorize button. Would appreciate some help as I am not sure what to check at this point.

**Comment by dnplus** [comment]
I guess it was the CORS problem.

You can try examples first with (to avoid misconfiguration)

```
streamlit run --server.enableCORS=false --server.enableXsrfProtection=false google.py
```

See if work or not

**Comment by dnplus** [comment]
close because no response
