### ISSUE TITLE
Authorization returns None as result

### ISSUE THREAD

**Issue by harithzulfaizal** [dnplus/streamlit-oauth#3]
Hi, I tested this out but after logging in through Google and Discord it redirects me to another authorize button in the popup that does nothing where the output results are None. Would appreciate any help, thanks! (Also posted on the Streamlit forum)

![image](https://github.com/dnplus/streamlit-oauth/assets/56865880/dfb7d45e-1261-4e17-9403-22b8cc9c35d0)

**Comment by dnplus** [comment]
Probably a CORS issue, can you share console/network information in browser developer console

**Comment by harithzulfaizal** [comment]
![image](https://github.com/dnplus/streamlit-oauth/assets/56865880/66e7b7b8-727e-463d-bcd5-ff527cbf6a27)

 Ah could be, the first 2 warnings pop out when clicking the button and the other/last 2 warnings after signing in. Am I correct in thinking that the code available in the url after signing in is the authorization code?

**Comment by mlvin** [comment]
Hey @dnplus @harithzulfaizal I got the same issue. What exactly was the solution for that problem?
