### ISSUE TITLE
SSLCertVerificationError after button click

### ISSUE THREAD

**Issue by m3xw3ll** [dnplus/streamlit-oauth#30]
Hello,

We have a local Keycloak instance running and I would like users of the Streamlit app to authenticate themselves via it. 
When the user clicks on the login button and enters his credentials the error message appears:

```python
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
```

How do I get rid of this error message?

**Comment by MattMacs** [comment]
Pushing this issue up... having the same problem running a local Authentik instance...
even bringing Streamlit to SSL with self-signed certificate doesn't help...

**Comment by dnplus** [comment]
I think you should try ignore ssl verify globally

for example

https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests

**Comment by MatthiasBeyens** [comment]
Same issue here, even after trying with the above.

**Comment by dnplus** [comment]
This component was built using httpx-oauth

refer to https://www.python-httpx.org/advanced/ssl/

It seems that httpx-oauth does not provide any interface to replace the httpx client. 

I am thinking about switching to authlib, but I'm not sure if it's a good idea. #39
