### ISSUE TITLE
discord oauth issue

### ISSUE THREAD

**Issue by Moj0mo** [dnplus/streamlit-oauth#34]
When discord authentication window pops up, the blue "authorize" button is stuck loading with 3 dots until it times out and is unclickable. 
![image](https://github.com/dnplus/streamlit-oauth/assets/81398697/ed99194e-eac5-4986-a7e9-5a0bf4fdfdc3)

**Comment by dnplus** [comment]
There is a discord sample code in examples

Not sure you try it or not
