### ISSUE TITLE
Maintain consistent style with authorize_button

### ISSUE THREAD

**Issue by rohitsathish** [dnplus/streamlit-oauth#37]
Currently ```oauth2.authorize_button``` style is inconsistent with streamlit, however ```oath2.refresh_token``` uses a regular streamlit button. Its better to maintain a consistent style. 

![image](https://github.com/dnplus/streamlit-oauth/assets/46263358/71cfe1b2-e6b0-443b-bbe7-640a7abc6a2d)

![image](https://github.com/dnplus/streamlit-oauth/assets/46263358/7420fbd0-991f-49a2-9a0c-d2c01405e21c)

**Comment by dnplus** [comment]
Currently have no idea how to inherit style from streamlit button

**Comment by MaraHochstein** [comment]
Could you add something like `background-color: var(--primary-color);` to button (like for button:hover) [here](https://github.com/dnplus/streamlit-oauth/blob/main/streamlit_oauth/frontend/style.css)? I think this works with primaryColor from config.toml

**Comment by dnplus** [comment]
@MaraHochstein 
noted

**Comment by MaraHochstein** [comment]
> Could you add something like `background-color: var(--primary-color);` to button (like for button:hover) [here](https://github.com/dnplus/streamlit-oauth/blob/main/streamlit_oauth/frontend/style.css)? I think this works with primaryColor from config.toml
@dnplus any news if that gets implemented?

**Comment by dnplus** [comment]
> > Could you add something like `background-color: var(--primary-color);` to button (like for button:hover) [here](https://github.com/dnplus/streamlit-oauth/blob/main/streamlit_oauth/frontend/style.css)? I think this works with primaryColor from config.toml
> > @dnplus any news if that gets implemented?

umm... need to make time to work on it
