### ISSUE TITLE
KeyError: 'st.session_state has no key "pkce-None"

### ISSUE THREAD

**Issue by jrowen** [dnplus/streamlit-oauth#48]
I'm seeing the following error with the latest release: `KeyError: 'st.session_state has no key "pkce-None"`.

File "/usr/local/lib/python3.9/site-packages/streamlit_oauth/__init__.py", line 103, in authorize_button
    del st.session_state[f'pkce-{key}']

**Comment by dnplus** [comment]
fix in 0.1.11 [1a95e10](https://github.com/dnplus/streamlit-oauth/commit/1a95e10b411fe9e293473e2a7a58506a2bd82468)
