### ISSUE TITLE
OAuth2Component.authorize_button() Not Returning Refresh Token

### ISSUE THREAD

**Issue by ACB-prgm** [dnplus/streamlit-oauth#5]
Hello,

When I call OAuth2Component.authorize_button(), It works (mostly) but I only get the access token and used auth code.  It also does not close the popup window which can confuse the end user. This is using the dropbox and google drive APIs.

response:
`{'code': 'xxx', 'state': '0334945248', 'token': {'access_token': 'xxx', 'token_type': 'bearer', 'expires_in': 14400, 'scope': 'account_info.read files.content.read files.metadata.read', 'uid': 'xxx', 'account_id': 'xxx', 'expires_at': 1694394686}}`

I know the flow returns a refresh token because I previously did this on my Flask app. Is there a reason for this? I would love it if you allowed the users a little more control over the process. I really only want the ability to handle the auth callback redirect, and Im sure other people have their own use cases.

**Comment by twyangqian** [comment]
I have same problem, authorize_button not return refresh token

**Comment by dnplus** [comment]
I noticed that they're using a non-standard parameter, "token_access_type=offline," to control the return of the refresh token. It might be a good idea to consider supporting this in the future, but it could require some changes to the httpx-oauth package.

**Comment by twyangqian** [comment]
Hi Dylan @dnplus 
I modify authorize_button that adding extras_params, then can set {'token_access_type': 'offline'} param when get authorization url. And I tested the new code, it can return refresh token after click authorize_button.
![image](https://github.com/dnplus/streamlit-oauth/assets/105896803/4db34fdb-c674-4043-ab31-186375bc7a36)

pull request url: https://github.com/dnplus/streamlit-oauth/pull/6
TKS~

**Comment by twyangqian** [comment]
self.oauth2.authorize_button("Continue with Google", self.redirect_uri, self.scope, key='authorize', extras_params={'access_type': 'offline'})

**Comment by dnplus** [comment]
Thanks @twyangqian 
Close with #6
